"""Shared plumbing for the code generators."""

from __future__ import annotations

import re

from ..checker import CheckedProgram
from ..errors import CheckError

RESERVED_PREFIX = "_pb"


def identifier(name: str, taken: set[str], keywords: set[str]) -> str:
    """Make a phonebook binding name safe to use in a target language."""
    candidate = re.sub(r"[^A-Za-z0-9_]", "_", name)
    if candidate in keywords or candidate.startswith(RESERVED_PREFIX):
        candidate += "_"
    while candidate in taken:
        candidate += "_"
    return candidate


def snake(name: str) -> str:
    return re.sub(r"[^a-z0-9_]", "_", name.lower())


def header(checked: CheckedProgram, target: str, comment: str) -> list[str]:
    """The provenance banner every generated file carries."""
    source = checked.program.path.replace("\\", "/")
    effects = ", ".join(sorted(checked.effects)) or "none"
    return [
        f"{comment} Generated by `dial emit --target {target}` from {source}",
        f"{comment} Do not edit: change the .phone source and regenerate.",
        f"{comment}",
        f"{comment} Every function called here is the {target} implementation of a",
        f"{comment} phonebook address. Swapping an implementation changes this file;",
        f"{comment} it never changes the program that produced it.",
        f"{comment}",
        f"{comment} declared effects: {effects}",
        "",
    ]


def fill(template: str, args: list[str]) -> str:
    """Apply an inline mapping template.

    `{0}`, `{1}`, ... are positional arguments; `{...}` is every argument, which
    is how the one variadic address (LIST) renders.
    """
    if "{...}" in template:
        return template.replace("{...}", ", ".join(args))
    try:
        return template.format(*args)
    except IndexError as exc:  # pragma: no cover - a malformed mapping table
        raise CheckError(f"inline template {template!r} wants more arguments") from exc
