"""Write tests/conformance/bits_random.phone: the bit operations and base
conversions on seeded random operands, so the two runtimes' hand-written
shifts, digit loops and digit readers are checked against each other on far
more cases than anyone would type.

Ints are drawn to reach the edges often: small values, values near the 64-bit
limits, and random bit patterns. Every base from 2 to 36 is used. Each number
written out is read back in the same base, so both directions are covered. The
seed is fixed, so rerunning this writes the same file; change the seed or the
counts only on purpose, then record the new expected output with
`dial conformance --record --backend python` and confirm Rust agrees.
"""

from __future__ import annotations

import random
from pathlib import Path

SEED = 20260929
CASES = 60


def an_int(rng: random.Random) -> int:
    """A 64-bit signed int, often at or near an edge."""
    kind = rng.random()
    if kind < 0.2:
        return rng.randint(-300, 300)
    if kind < 0.35:
        return rng.choice([-(2**63), 2**63 - 1]) + rng.randint(-3, 3) * (1 if rng.random() < 0.5 else 0)
    bits = rng.getrandbits(64)
    return bits - 2**64 if bits >= 2**63 else bits


def clamp64(value: int) -> int:
    return max(-(2**63), min(2**63 - 1, value))


def a_count(rng: random.Random) -> int:
    return rng.choice([0, 1, 63, 64, 65, rng.randint(0, 63), rng.randint(0, 63), rng.randint(64, 10**6)])


def main() -> None:
    rng = random.Random(SEED)
    lines = [
        "phonebook 0.1",
        "",
        "# Generated by scripts/gen_bits_random.py. Do not edit by hand.",
        "#",
        "# Each block applies the bit operations and base conversions to seeded",
        "# random operands and prints the results, so every line of output is a",
        "# place the Python and Rust runtimes, each written by hand, must agree.",
    ]
    for case in range(CASES):
        a, b = clamp64(an_int(rng)), clamp64(an_int(rng))
        count = a_count(rng)
        base = rng.randint(2, 36)
        big = rng.randrange(0, 10 ** rng.randint(1, 300)) * rng.choice([-1, 1])
        calls = [
            ("400-0000160", f"{a}, {b}", "and"),
            ("400-0000161", f"{a}, {b}", "or"),
            ("400-0000162", f"{a}, {b}", "xor"),
            ("400-0000163", f"{a}", "not"),
            ("400-0000164", f"{a}, {count}", "shl"),
            ("400-0000165", f"{a}, {count}", "shr"),
            ("400-0000166", f"{a}, {count}", "ushr"),
            ("400-0000167", f"{a}", "count"),
            ("400-0000168", f"{a}, {base}", "text"),
            ("400-0000169", f"text_{case}, {base}, 0", "back"),
            ("400-0000170", f"{b}, {base}", "pattern"),
            ("400-0000171", f"pattern_{case}, {base}, 0", "pattern_back"),
            ("400-0000172", f"{big}n, {base}", "big_text"),
            ("400-0000173", f"big_text_{case}, {base}, 0n", "big_back"),
        ]
        lines.append("")
        for address, args, name in calls:
            out = f"{name}_{case}"
            lines.append(f"{address}@[{args}] -> {out}")
            lines.append(f"100-0000001@[{out}]")
    path = Path(__file__).resolve().parent.parent / "tests" / "conformance" / "bits_random.phone"
    path.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    print(f"wrote {path}")


if __name__ == "__main__":
    main()
