"""Write tests/conformance/bigint_random.phone: bigint arithmetic on seeded
random operands, for the Rust runtime's hand-written arithmetic to be checked
against Python's own int.

The operands are skewed toward the places a base-10^9 implementation breaks:
lengths just either side of a limb, runs of nines and zeros, and divisors of
every size up to the dividend's. The seed is fixed, so rerunning this writes
the same file; change the seed or the counts only on purpose, then record the
new expected output with `dial conformance --record --backend python` and
confirm Rust agrees.
"""

from __future__ import annotations

import random
from pathlib import Path

SEED = 20260928
CASES = 60

OPS = [
    ("400-0000025", "ADD_BIG"),
    ("400-0000026", "SUB_BIG"),
    ("400-0000027", "MUL_BIG"),
    ("400-0000028", "DIV_BIG"),
    ("400-0000029", "MOD_BIG"),
]


def operand(rng: random.Random, max_digits: int) -> int:
    shape = rng.randrange(6)
    digits = rng.choice([1, 8, 9, 10, 17, 18, 19, 27, 28, rng.randint(1, max_digits)])
    digits = min(digits, max_digits)
    if shape == 0:
        value = 10**digits - 1  # all nines
    elif shape == 1:
        value = 10 ** (digits - 1)  # one then zeros
    elif shape == 2:
        value = 10 ** (digits - 1) + rng.randrange(0, 3)
    else:
        value = rng.randrange(10 ** (digits - 1), 10**digits)
    return -value if rng.random() < 0.5 else value


def main() -> None:
    rng = random.Random(SEED)
    lines = [
        "phonebook 0.1",
        "",
        "# Generated by scripts/gen_bigint_random.py. Do not edit by hand.",
        "#",
        "# Each block applies all five bigint operations to one pair of seeded",
        "# random operands and prints the results, so every line of output is a",
        "# place Python's int and the Rust runtime's own arithmetic must agree.",
    ]
    for case in range(CASES):
        a = operand(rng, 120)
        b = operand(rng, rng.choice([9, 20, 60, 120]))
        lines.append("")
        for address, name in OPS:
            out = f"{name.lower()}_{case}"
            lines.append(f"{address}@[{a}n, {b}n] -> {out}")
            lines.append(f"100-0000001@[{out}]")
    for case in range(10):
        base = operand(rng, 30)
        # Keep under the ceiling: the digits multiply, roughly, with the power.
        exponent = rng.randint(0, min(200, 3900 // len(str(abs(base)))))
        lines.append("")
        lines.append(f"400-0000030@[{base}n, {exponent}] -> pow_{case}")
        lines.append(f"100-0000001@[pow_{case}]")
    path = Path(__file__).resolve().parent.parent / "tests" / "conformance" / "bigint_random.phone"
    path.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    print(f"wrote {path}")


if __name__ == "__main__":
    main()
