"""Write tests/conformance/decimal_random.phone: decimal arithmetic on seeded
random operands, so the two hand-written decimal types, Python's and Rust's,
are checked against each other on far more cases than anyone would type.

The operands are skewed toward where a decimal implementation breaks: scales
that differ, runs of nines that carry, values that sit exactly on a half when
rounded, and coefficients either side of a 10^9 limb. The seed is fixed, so
rerunning this writes the same file; change the seed or the counts only on
purpose, then record the new expected output with
`dial conformance --record --backend python` and confirm Rust agrees.
"""

from __future__ import annotations

import random
from pathlib import Path

SEED = 20260928
CASES = 60


def operand(rng: random.Random) -> str:
    """A decimal literal, without its `d`."""
    scale = rng.choice([0, 1, 2, 2, 3, 5, 9, 10, 18, rng.randint(0, 40)])
    digits = rng.choice([1, 2, 8, 9, 10, 18, 19, 28, rng.randint(1, 60)])
    shape = rng.randrange(5)
    if shape == 0:
        coefficient = 10**digits - 1  # all nines
    elif shape == 1:
        coefficient = 10 ** (digits - 1)  # one then zeros
    elif shape == 2:
        coefficient = 10 ** (digits - 1) * 5  # a five then zeros: halves
    else:
        coefficient = rng.randrange(10 ** (digits - 1), 10**digits)
    if rng.random() < 0.05:
        coefficient = 0
    text = str(coefficient).rjust(scale + 1, "0")
    if scale:
        text = text[:-scale] + "." + text[-scale:]
    return ("-" if coefficient and rng.random() < 0.5 else "") + text


def main() -> None:
    rng = random.Random(SEED)
    lines = [
        "phonebook 0.1",
        "",
        "# Generated by scripts/gen_decimal_random.py. Do not edit by hand.",
        "#",
        "# Each block applies the decimal operations to one pair of seeded random",
        "# operands and prints the results, so every line of output is a place the",
        "# Python and Rust decimal types, each written by hand, must agree.",
    ]
    for case in range(CASES):
        a, b = operand(rng), operand(rng)
        places = rng.choice([0, 1, 2, 4, 9, 20])
        lines.append("")
        calls = [
            ("400-0000043", f"{a}d, {b}d", "add"),
            ("400-0000044", f"{a}d, {b}d", "sub"),
            ("400-0000045", f"{a}d, {b}d", "mul"),
            ("400-0000047", f"{a}d, {places}", "round"),
            ("400-0000042", f"{a}d", "trunc") if len(a.split(".")[0].lstrip("-")) < 19 else None,
            ("400-0000049", f"{a}d", "float"),
        ]
        if b.strip("-0.") != "":
            calls.append(("400-0000046", f"{a}d, {b}d, {places}", "div"))
        for call in calls:
            if call is None:
                continue
            address, args, name = call
            out = f"{name}_{case}"
            lines.append(f"{address}@[{args}] -> {out}")
            lines.append(f"100-0000001@[{out}]")
    path = Path(__file__).resolve().parent.parent / "tests" / "conformance" / "decimal_random.phone"
    path.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    print(f"wrote {path}")


if __name__ == "__main__":
    main()
