"""Write tests/conformance/printing_random.phone: FORMAT_FLOAT and
FORMAT_FRACTION on seeded random values, so the two hand-written printers,
Python's and Rust's, are checked against each other on far more cases than
anyone would type.

The floats are skewed toward where a printer breaks: values whose shown digits
end in a 5 (a half at the last place kept), runs of nines that carry, and
magnitudes from subnormal to near the largest float. The fractions use parts
near the 64-bit edges. The seed is fixed, so rerunning this writes the same
file; change the seed or the counts only on purpose, then record the new
expected output with `dial conformance --record --backend python` and confirm
Rust agrees.
"""

from __future__ import annotations

import random
import struct
from pathlib import Path

SEED = 20260928
CASES = 60


def a_float(rng: random.Random) -> float:
    shape = rng.randrange(5)
    if shape == 0:  # any bit pattern that is a finite, non-negative-zero float
        while True:
            value = struct.unpack("<d", rng.getrandbits(64).to_bytes(8, "little"))[0]
            if value == value and abs(value) != float("inf") and str(value) != "-0.0":
                return value
    if shape == 1:  # shown digits end in a 5
        digits = rng.randint(1, 15)
        return float(f"{rng.randrange(10**digits)}5e{rng.randint(-digits - 8, 3)}")
    if shape == 2:  # a run of nines
        return float("9" * rng.randint(1, 16) + f"e{rng.randint(-20, 5)}")
    if shape == 3:
        return rng.uniform(-1000, 1000)
    return rng.choice([-1, 1]) * rng.random() * 10 ** rng.randint(-30, 30)


def an_int(rng: random.Random, positive: bool = False) -> int:
    value = rng.choice(
        [rng.randint(1, 9), rng.randint(1, 10**6), 2**63 - 1 - rng.randint(0, 5), rng.randint(1, 2**63 - 1)]
    )
    if not positive and rng.random() < 0.5:
        value = -value
    return value


def main() -> None:
    rng = random.Random(SEED)
    lines = [
        "phonebook 0.1",
        "",
        "# Generated by scripts/gen_printing_random.py. Do not edit by hand.",
        "#",
        "# Each block prints one seeded random float and one random fraction to a",
        "# number of places, so every line of output is a place the Python and Rust",
        "# printers, each written by hand, must agree.",
    ]
    for case in range(CASES):
        value = a_float(rng)
        places = rng.choice([0, 1, 2, 3, 6, 17, 40])
        top, bottom = an_int(rng), an_int(rng, positive=True)
        fraction_places = rng.choice([0, 1, 2, 5, 20, 45])
        lines += [
            "",
            f"400-0000120@[{value!r}, {places}] -> float_{case}",
            f"100-0000001@[float_{case}]",
            f"400-0000080@[{top}, {bottom}] -> fraction_{case}",
            f"400-0000122@[fraction_{case}, {fraction_places}] -> shown_{case}",
            f"100-0000001@[shown_{case}]",
        ]
    target = Path(__file__).resolve().parent.parent / "tests" / "conformance" / "printing_random.phone"
    target.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    print(f"wrote {target}")


if __name__ == "__main__":
    main()
