"""Write tests/conformance/list_maths_random.phone: smallest, largest, sum,
average and median over seeded random lists of every number type, so the two
runtimes' hand-written list maths is checked against each other on far more
lists than anyone would type.

Floats are drawn from their bits now and then, so huge, tiny and subnormal
values meet in one list and the midpoint and the running sum reach their
edges. The seed is fixed, so rerunning this writes the same file; change the
seed or the counts only on purpose, then record the new expected output with
`dial conformance --record --backend python` and confirm Rust agrees.
"""

from __future__ import annotations

import math
import random
import struct
from pathlib import Path

SEED = 20260929
CASES = 40


def a_float(rng: random.Random) -> float:
    """A finite float, mostly plain, sometimes from random bits."""
    while True:
        roll = rng.random()
        if roll < 0.5:
            value = round(rng.uniform(-1000, 1000), rng.randint(0, 3))
        elif roll < 0.7:
            value = rng.choice([0.1, 0.2, 0.3, 0.7, 1e16, -1e16, 1.0, 0.5])
        else:
            (value,) = struct.unpack("<d", struct.pack("<Q", rng.getrandbits(64)))
            # Keep sums finite most of the time: SUM_FLOAT of two huge values
            # is an overflow error, which would stop the program.
            if abs(value) > 1e300:
                continue
        if math.isfinite(value):
            return value


def a_decimal(rng: random.Random) -> str:
    """A decimal literal, without its `d`."""
    scale = rng.choice([0, 1, 2, 2, 4, rng.randint(0, 20)])
    digits = rng.choice([1, 2, 5, 19, rng.randint(1, 40)])
    coefficient = rng.randrange(10 ** (digits - 1), 10**digits)
    text = str(coefficient).rjust(scale + 1, "0")
    if scale:
        text = text[:-scale] + "." + text[-scale:]
    return ("-" if rng.random() < 0.4 else "") + text


def a_list(rng: random.Random, make) -> str:
    return ", ".join(make() for _ in range(rng.randint(1, 9)))


def main() -> None:
    rng = random.Random(SEED)
    lines = [
        "phonebook 0.1",
        "",
        "# Generated by scripts/gen_list_maths_random.py. Do not edit by hand.",
        "#",
        "# Each block builds seeded random lists of every number type and prints",
        "# their smallest, largest, sum, average and median, so every line of output",
        "# is a place the Python and Rust runtimes, each written by hand, must agree.",
    ]
    for case in range(CASES):
        ints = a_list(rng, lambda: str(rng.choice([rng.randint(-100, 100), rng.randint(-(2**63), 2**63 - 1)])))
        floats = a_list(rng, lambda: repr(a_float(rng)))
        bigs = a_list(rng, lambda: f"{rng.randrange(-(10 ** rng.randint(1, 80)), 10 ** rng.randint(1, 80))}n")
        decs = a_list(rng, lambda: a_decimal(rng) + "d")
        places = rng.choice([0, 1, 2, 3, 8, 25])
        count = rng.randint(1, 7)
        fractions = [(rng.randint(-(10**6), 10**6), rng.randint(1, 60)) for _ in range(count)]
        lines.append("")
        lines.append(f"300-0000001@[{ints}] -> ints_{case}")
        lines.append(f"300-0000001@[{floats}] -> floats_{case}")
        lines.append(f"300-0000001@[{bigs}] -> bigs_{case}")
        lines.append(f"300-0000001@[{decs}] -> decs_{case}")
        for index, (top, bottom) in enumerate(fractions):
            lines.append(f"400-0000080@[{top}, {bottom}] -> f{index}_{case}")
        names = ", ".join(f"f{index}_{case}" for index in range(count))
        lines.append(f"300-0000001@[{names}] -> fracs_{case}")
        calls = []
        for kind in ("ints", "floats", "bigs", "decs", "fracs"):
            calls.append(("400-0000180", f"{kind}_{case}", f"small_{kind}"))
            calls.append(("400-0000181", f"{kind}_{case}", f"large_{kind}"))
        calls += [
            ("400-0000182", f"floats_{case}", "sum_floats"),
            ("400-0000183", f"bigs_{case}", "sum_bigs"),
            ("400-0000184", f"decs_{case}", "sum_decs"),
            ("400-0000185", f"fracs_{case}", "sum_fracs"),
            ("400-0000186", f"ints_{case}, {places}", "avg_ints"),
            ("400-0000187", f"floats_{case}", "avg_floats"),
            ("400-0000188", f"bigs_{case}, {places}", "avg_bigs"),
            ("400-0000189", f"decs_{case}, {places}", "avg_decs"),
            ("400-0000190", f"fracs_{case}", "avg_fracs"),
            ("400-0000191", f"ints_{case}", "med_ints"),
            ("400-0000192", f"floats_{case}", "med_floats"),
            ("400-0000193", f"bigs_{case}", "med_bigs"),
            ("400-0000194", f"decs_{case}", "med_decs"),
            ("400-0000195", f"fracs_{case}", "med_fracs"),
        ]
        for address, args, name in calls:
            out = f"{name}_{case}"
            lines.append(f"{address}@[{args}] -> {out}")
            lines.append(f"100-0000001@[{out}]")
    path = Path(__file__).resolve().parent.parent / "tests" / "conformance" / "list_maths_random.phone"
    path.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    print(f"wrote {path}")


if __name__ == "__main__":
    main()
