"""Write tests/conformance/roots_random.phone: square roots, floors, ceilings
and remainders on seeded random operands, so the two runtimes' hand-written
roots and the rounding around them are checked against each other on far more
cases than anyone would type.

Float operands are drawn from their bits, so every exponent is reached,
subnormals included. The seed is fixed, so rerunning this writes the same
file; change the seed or the counts only on purpose, then record the new
expected output with `dial conformance --record --backend python` and confirm
Rust agrees.
"""

from __future__ import annotations

import math
import random
import struct
from pathlib import Path

SEED = 20260929
CASES = 60


def a_float(rng: random.Random) -> float:
    """A finite float from random bits, or a plain one now and then."""
    while True:
        if rng.random() < 0.3:
            value = rng.choice([rng.uniform(-100, 100), float(rng.randint(-50, 50)) + 0.5])
        else:
            (value,) = struct.unpack("<d", struct.pack("<Q", rng.getrandbits(64)))
        if math.isfinite(value):
            return value


def a_decimal(rng: random.Random, negative: bool = True) -> str:
    """A decimal literal, without its `d`."""
    scale = rng.choice([0, 1, 2, 4, 9, rng.randint(0, 30)])
    digits = rng.choice([1, 2, 9, 10, 19, rng.randint(1, 50)])
    coefficient = rng.randrange(10 ** (digits - 1), 10**digits)
    if rng.random() < 0.2:
        coefficient = (rng.randrange(1, 10**6)) ** 2  # perfect squares
    text = str(coefficient).rjust(scale + 1, "0")
    if scale:
        text = text[:-scale] + "." + text[-scale:]
    return ("-" if negative and rng.random() < 0.5 else "") + text


def main() -> None:
    rng = random.Random(SEED)
    lines = [
        "phonebook 0.1",
        "",
        "# Generated by scripts/gen_roots_random.py. Do not edit by hand.",
        "#",
        "# Each block applies the root, floor, ceiling and remainder operations to",
        "# seeded random operands and prints the results, so every line of output",
        "# is a place the Python and Rust runtimes, each written by hand, must agree.",
    ]
    for case in range(CASES):
        x, y = a_float(rng), a_float(rng)
        n = rng.choice([rng.randrange(0, 2**63), rng.randrange(0, 10**6), rng.randrange(0, 3037000500) ** 2])
        big = rng.randrange(0, 10 ** rng.randint(1, 200))
        a, b = a_decimal(rng), a_decimal(rng)
        root_of = a.lstrip("-")
        places = rng.choice([0, 1, 2, 5, 10, 30])
        p, q = rng.randint(-(10**9), 10**9), rng.randint(1, 10**9)
        r, s = rng.choice([-1, 1]) * rng.randint(1, 10**9), rng.randint(1, 10**9)
        calls = [
            ("400-0000140", f"{abs(x)!r}", "sqrt"),
            ("400-0000141", f"{x!r}", "floor"),
            ("400-0000142", f"{x!r}", "ceil"),
            ("400-0000143", f"{x!r}, {y!r}", "fmod") if y != 0.0 else None,
            ("400-0000144", f"{n}", "isqrt"),
            ("400-0000145", f"{big}n", "isqrt_big"),
            ("400-0000146", f"{root_of}d, {places}", "sqrt_dec"),
            ("400-0000147", f"{a}d", "floor_dec"),
            ("400-0000148", f"{a}d", "ceil_dec"),
            ("400-0000149", f"{a}d, {b}d", "mod_dec"),
        ]
        lines.append("")
        for call in calls:
            if call is None:
                continue
            address, args, name = call
            out = f"{name}_{case}"
            lines.append(f"{address}@[{args}] -> {out}")
            lines.append(f"100-0000001@[{out}]")
        lines.append(f"400-0000080@[{p}, {q}] -> frac_a_{case}")
        lines.append(f"400-0000080@[{r}, {s}] -> frac_b_{case}")
        lines.append(f"400-0000150@[frac_a_{case}] -> ceil_frac_{case}")
        lines.append(f"100-0000001@[ceil_frac_{case}]")
        lines.append(f"400-0000151@[frac_a_{case}, frac_b_{case}] -> mod_frac_{case}")
        lines.append(f"100-0000001@[mod_frac_{case}]")
    path = Path(__file__).resolve().parent.parent / "tests" / "conformance" / "roots_random.phone"
    path.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    print(f"wrote {path}")


if __name__ == "__main__":
    main()
